name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  IMAGE_REPOSITORY: sveltekit-app
  CONTAINER_REGISTRY: ghcr.io
  DOCKERFILE_PATH: ./Dockerfile
  VERSION_PREFIX: 1.0.0
  LATEST_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js for npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Assuming a recent Node.js version for SvelteKit
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci # Use npm ci for clean installs in CI environments

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.REPO_NAME }}:${{ env.VERSION_PREFIX }}-${{ github.run_id }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.REPO_NAME }}:${{ env.LATEST_TAG }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
